services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - NODE_ENV=development
    depends_on:
      - central-registry

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./backend/src:/app/src
    environment:
      - NODE_ENV=development
      - PORT=3000

  central-registry:
    build:
      context: ./backend
      dockerfile: central-registry/Dockerfile
    ports:
      - "4000:4000"

  blockchain-server-1:
    build:
      context: ./backend
      dockerfile: blockchain-server/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - central-registry
    environment:
      - PORT=3000

  blockchain-server-2:
    build:
      context: ./backend
      dockerfile: blockchain-server/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - central-registry
    environment:
      - PORT=3001

  miner:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - central-registry

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - central-registry
    environment:
      - NODE_ENV=development

networks:
  default:
    driver: bridge
